name: Publish Package

on:
  workflow_run:
    workflows:
      - 'Release'
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - uses: actions/cache@v3
        with:
          path: dist
          key: ${{ github.run_number }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: pnpm build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - uses: actions/cache@v3
        with:
          path: dist
          key: ${{ github.run_number }}
      - run: npm pkg delete scripts.prepare
      - run: npm pkg delete devDependencies
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - uses: actions/cache@v3
        with:
          path: dist
          key: ${{ github.run_number }}
      - run: npm pkg delete scripts.prepare
      - run: npm pkg delete devDependencies
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
